fix: x,y offset responsive
graasp/graasp-app-name-the-frame pull request #131
Opened 2024-08-02 12:43 UTC by LinaYahya

closes #130

2024-08-08 13:03 UTC, pyphilia requested changes
Thanks for the changes, I think we can even more improve this code, let me know if you have questions!

2024-08-08 13:03 UTC, pyphilia commented on src/modules/context/imageDimensionContext.tsx
> +type Props1 = {
```suggestion
type Props = {
```

2024-08-08 13:03 UTC, pyphilia commented on src/modules/context/imageDimensionContext.tsx
> +export const ImageDimensionsProvider = ({ children }: Props1): JSX.Element => {
Add comments why image dimensions are necessary.

2024-08-12 07:16 UTC, ReidyT approved these changes
Thanks for you PR, LGTM 🤠 I just let some suggestions

2024-08-12 07:16 UTC, ReidyT commented on src/modules/common/PlayerFrame.tsx
>    const onDragEnd = (draggable: DropResult): void => {
`onDragEnd` is a bit long, what do you think about extracting some of its logic in smaller functions ?

2024-08-13 12:18 UTC, ReidyT approved these changes
Thanks for your work and your changes! I just let some suggestions 😆

2024-08-13 12:18 UTC, ReidyT commented on src/utils/dnd.ts
> +  const handleMoveFromAll = ({
Maybe I'd finally put these three functions outside the trackLabelsChanges to improve a bit the readability of this function 😅

2024-08-13 12:18 UTC, ReidyT commented on src/utils/dnd.ts
> +export const trackLabelsChanges = ({
What do you think about this suggestion ?

```suggestion
export const handleMoveLabel = ({
```

2024-08-15 08:04 UTC, merged