feat: preview step
graasp/graasp-app-name-the-frame pull request #95
Opened 2024-07-08 08:00 UTC by LinaYahya

closes #65

2024-08-05 12:22 UTC, pyphilia requested changes
Thanks for the PR! It's not really clear how it works however, if you could explain what are labels and how you "compute" the key components such as "choices" and "to be filled boxes".
Also for image dimensions I'm not sure it's a good idea to save it in settings.

2024-08-05 12:22 UTC, pyphilia commented on src/utils/index.ts
> +  return (...args: any[]) => {
Not sure it works.
```suggestion
  return (...args: unknown[]) => {
```

2024-08-07 08:36 UTC, LinaYahya commented on src/modules/builder/configuration/AddImageStep.tsx
> +    const newData = { ...(settings && settings.data), description };
it going to be an empty object

2024-08-07 08:38 UTC, LinaYahya commented on src/modules/builder/configuration/AddLabelsStep/DraggableLabel.tsx
> +    }
I already omitted it within the fix of x, y offset for the add labels step, So I think we can keep it for now as we are going to discard it anyway.

2024-08-07 08:39 UTC, LinaYahya commented on src/modules/common/ImageFrame.tsx
> +  const appSettingId = image?.[0]?.id || '';
unfortunately `useAppSettingFile` not accepting undefined

2024-08-07 12:09 UTC, merged